sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: ADswwImRYV/IcqmlAMfHA8ytnxyJ5S4iP9KIFdIr9vFh7B0S4m8RtwfGD13NyjIMjVnODKXeHRAmTMlDsAL70vKOCOAsA3HXLUqxcffsvHPIqGto2qHhLQSCBMpQaze4/j07vU82a1JX45RG7UOpBWn9siaT52+OljMHs/WLTjM=
  email:
    recipients:
      secure: W5qNNrMmasDNIcA52MKhxPbZg0amnrj925LS3Gp6/7EHna+5uV3q9CwVt8YfU7/AtR4MN0qyyGMv4P/A9WnHFqsePyrNMY7JvZKMg+tugc52aUDuKNT+DCJXqqrkmr4/P4csjfzU+dIp+Ad0v/aErm51XtUbSA2lNr59ESjKpmY=
